LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)
LOCAL_SRC_FILES:= math.c
LOCAL_MODULE := math
LOCAL_C_INCLUDES += 
LOCAL_SHARED_LIBRARIES :=
LOCAL_LDLIBS := -L$(SYSROOT)/usr/lib -llog 
include $(BUILD_SHARED_LIBRARY)



